CREATE TABLE IF NOT EXISTS water_dispense_order (
    id               BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    order_no         VARCHAR(32)  NOT NULL COMMENT 'Scan water order number',
    customer_id      BIGINT                COMMENT 'Customer user id',
    device_id        VARCHAR(64)  NOT NULL COMMENT 'Device ID',
    sn               VARCHAR(64)  NOT NULL COMMENT 'Device SN',
    target_ml        BIGINT       NOT NULL COMMENT 'Target water volume in ml',
    pay_amount       BIGINT       NOT NULL DEFAULT 1 COMMENT 'Pay amount in cents',
    pay_status       VARCHAR(32)  NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/SUCCESS/FAIL/REFUND',
    dispense_status  VARCHAR(32)  NOT NULL DEFAULT 'PENDING_PAY' COMMENT 'PENDING_PAY/PAID/DISPATCHED/DISPENSING/COMPLETED/FAILED/REFUNDING/REFUNDED',
    command_status   VARCHAR(32)  NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/SENT/ACK/FAILED',
    q74_payload      VARCHAR(255)          COMMENT 'Q74 protocol payload',
    transaction_id   VARCHAR(64)           COMMENT 'Payment transaction id',
    payment_provider VARCHAR(32)            COMMENT 'Payment provider: MOCK/WECHAT',
    prepay_id        VARCHAR(128)           COMMENT 'WeChat Pay prepay_id',
    wx_open_id       VARCHAR(128)           COMMENT 'Payer mini program openid',
    mock_payment     TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '1=mock payment',
    paid_at          DATETIME(3)           COMMENT 'Paid time',
    command_sent_at  DATETIME(3)           COMMENT 'Q74 command sent time',
    completed_at     DATETIME(3)           COMMENT 'Completed time',
    remark           VARCHAR(255)          COMMENT 'Remark',
    created_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    created_by       BIGINT                COMMENT 'Created by',
    updated_by       BIGINT                COMMENT 'Updated by',
    deleted          TINYINT(1)   NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_water_dispense_order_no (order_no),
    KEY idx_water_dispense_customer_id (customer_id),
    KEY idx_water_dispense_device_id (device_id),
    KEY idx_water_dispense_sn (sn),
    KEY idx_water_dispense_prepay_id (prepay_id),
    UNIQUE KEY uk_water_dispense_transaction_id (transaction_id),
    KEY idx_water_dispense_status (dispense_status),
    KEY idx_water_dispense_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Scan water dispense order';

CREATE TABLE IF NOT EXISTS water_dispense_event (
    id              BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    order_no        VARCHAR(32)  NOT NULL COMMENT 'Scan water order number',
    event_type      VARCHAR(64)  NOT NULL COMMENT 'Event type',
    event_status    VARCHAR(32)  NOT NULL COMMENT 'SUCCESS/FAIL',
    event_message   VARCHAR(255)          COMMENT 'Event message',
    raw_data        TEXT                  COMMENT 'Raw event data',
    created_at      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    created_by      BIGINT                COMMENT 'Created by',
    updated_by      BIGINT                COMMENT 'Updated by',
    deleted         TINYINT(1)   NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_water_dispense_event_order_no (order_no),
    KEY idx_water_dispense_event_type (event_type),
    KEY idx_water_dispense_event_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Scan water dispense event';
